### ISSUE TITLE
Wrong package and environment ID

### ISSUE THREAD

**Issue by scevie** [secury/optidice#1]
Hi, I would like to reproduce your code. However, env_name cannot be found in gym.

gym.error.unregisteredEnv: No registered env with id :walker2d-medium-export-v0.
All ids cannot run

**Comment by secury** [comment]
Hi, you should install d4rl.
Also, walker2d-medium-exp**o**rt-v0 -> walker2d-medium-exp**e**rt-v0.

**Comment by scevie** [comment]
Thank you
